# Generated by Django 2.2.3 on 2019-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190905_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Está ativo?'),
        ),
    ]
