# Generated by Django 2.2.3 on 2019-09-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariosmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Autorizado em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.UsuariosModel')),
            ],
        ),
    ]
